[colors]
[colors.primary]
background = "#121212"
foreground = "#ffffff"

[colors.normal]
black   = "#121212"
red     = "#d06057"
green   = "#79bcbe"
yellow  = "#d58c71"
blue    = "#8e99c8"
magenta = "#cd989d"
cyan    = "#68b4b6"
white   = "#ffffff"

[colors.bright]
black   = "#9e9e9e"
red     = "#e8a19b"
green   = "#b5ddde"
yellow  = "#ecc4b5"
blue    = "#cad0e7"
magenta = "#ecd5d7"
cyan    = "#7cc9cb"
white   = "#ffffff"

[colors.cursor]
text   = "#121212"
cursor = "#ffffff"
