force_keyboard_focus = true
selection_wrap = true
hide_action_hints = true
hide_action_hints_dmenu = true
theme = "custom"

[shell]
layer = "overlay"
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = " Search...", list = "" }

[keybinds]
quick_activate = []

[columns]
symbols = 1

[providers]
max_results = 0
default = []
empty = []
