force_keyboard_focus = true                                               
selection_wrap = true                                                      
hide_action_hints = true                                                    

[placeholders]
"default" = { input = "ï€‚ Search...", list = "No Results" }

[keybinds]
quick_activate = []

[columns]
symbols = 1

[providers]
max_results = 256 
default = [
  "desktopapplications",
  "websearch",
]
