format = """
$directory\
$git_branch\
$git_status"""

add_newline = false

[directory]
truncation_length = 1
read_only = ' ðŸ”’'

[git_branch]
symbol = 'git'
format = '[$symbol:\([$branch](bold red)\)](bold blue) '

[git_status]
format     = '[$all_status]($style)'
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "î®« "
up_to_date = "ï€Œ "
untracked  = "? "
modified   = "î©± "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
